### ISSUE TITLE
[17.0] installing maintenance timesheet trigger error

### ISSUE THREAD

**Issue by imunisasi** [OCA/maintenance#430] opened 2024-09-27 02:07 UTC
## Module
The name of the module that has a bug.
maintenance_timesheet

1. Install Odoo Enterprise
2. Install Maintenance Timesheet

## Describe the bug
After installing there is warning like this :

```
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 1770, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo-server/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo-server/odoo/http.py", line 1797, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo-server/odoo/http.py", line 2001, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo-server/odoo/http.py", line 725, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/odoo-server/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-77>", line 2, in button_immediate_install
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 466, in button_immediate_install
    return self._button_immediate_function(self.env.registry[self._name].button_install)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 590, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/opt/odoo/odoo-server/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/odoo-server/odoo/modules/loading.py", line 480, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/opt/odoo/odoo-server/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/odoo-server/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/opt/odoo/odoo-server/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/opt/odoo/odoo-server/odoo/tools/convert.py", line 627, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/opt/odoo/odoo-server/odoo/tools/convert.py", line 693, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo/odoo-server/odoo/tools/convert.py", line 613, in parse
    self._tag_root(de)
  File "/opt/odoo/odoo-server/odoo/tools/convert.py", line 567, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /opt/odoo/odoo-server/addons/sale_timesheet/report/timesheets_analysis_views.xml:119
Error while validating view near:

<search string="Timesheet Report" __validate__="1">
                <field name="name"/>
                <field name="maintenance_request_id"/>
                <field name="date"/>

Field "maintenance_request_id" does not exist in model "timesheets.analysis.report"

View error context:
{'file': '/opt/odoo/odoo-server/addons/sale_timesheet/report/timesheets_analysis_views.xml',
 'line': 2,
 'name': 'timesheets.analysis.report.search',
 'view': ir.ui.view(1987,),
 'view.model': 'timesheets.analysis.report',
 'view.parent': ir.ui.view(1964,),
 'xmlid': 'hr_timesheet_report_search_sale_timesheet'}


The above server error caused the following client error:
RPC_ERROR://xxx/web/assets/8327161/web.assets_web.min.js:2870:163)
    at XMLHttpRequest.<anonymous> (https://xxx/web/assets/8327161/web.assets_web.min.js:2874:13)
```

When open Internal Maintenance in Maintenance
```
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://xxx/web/assets/763fb28/web.assets_web.min.js:916:101)
    at App.handleError (https://xxx/web/assets/763fb28/web.assets_web.min.js:1542:29)
    at ComponentNode.initiateRender (https://xxx/web/assets/763fb28/web.assets_web.min.js:1006:19)

Caused by: TypeError: Cannot read properties of undefined (reading 'type')
    at https://xxx/web/assets/763fb28/web.assets_web.min.js:8912:126
    at visit (https://xxx/web/assets/763fb28/web.assets_web.min.js:4218:51)
    at visitChildren (https://xxx/web/assets/763fb28/web.assets_web.min.js:4217:171)
    at visit (https://xxx/web/assets/763fb28/web.assets_web.min.js:4218:129)
    at visitXML (https://xxx/web/assets/763fb28/web.assets_web.min.js:4218:202)
    at KanbanArchParser.parse (https://xxx/web/assets/763fb28/web.assets_web.min.js:8909:2326)
    at Object.props (https://xxx/web/assets/763fb28/web.assets_web.min.js:9183:1128)
    at View.loadView (https://xxx/web/assets/763fb28/web.assets_web.min.js:9820:179)
    at async Promise.all (index 0)
    at async ComponentNode.initiateRender (https://xxx/web/assets/763fb28/web.assets_web.min.js:1005:36)
```

**Comment by pedrobaeza** [comment] 2024-09-27 05:55
It seems you are importing the module instead of adding the module to the addons path. The import option is just for data modules.

**Comment by imunisasi** [comment] 2024-09-27 17:16
hello @pedrobaeza ,
i put module in addons path, restart odoo, update app and then installing it
is that right way ?

thanks for responding

**Comment by pedrobaeza** [comment] 2024-09-27 17:19
Yes, but something in your deployment seems incorrect, as the error is not even in `maintenance_timesheet`, but on `sale_timesheet`, so you should check how you are deploying. Closing as this is not a bug of the module. You can ask for more assistance on forums.

**Closed as completed by pedrobaeza** 2024-09-27 17:19 UTC
Labels: bug
